export const brand = {
  name: "BST",
  legalName: "BST Business Support Technology Ltd",
  logo: "/bst-logo.jpg",
  tagline: "Websites, performance marketing, and growth systems.",
  whatsapp: process.env.NEXT_PUBLIC_WHATSAPP || "966500000000",
  email: process.env.NEXT_PUBLIC_EMAIL || "hello@growbiz.digital",
};

export const copy = {
  navHome: "Home",
  navProjects: "Work",
  navContact: "Contact",
  navAdmin: "Admin",
  navServices: "Services",
  navReviews: "Reviews",
  menuOpen: "Menu",
  menuClose: "Close",
  headerDescriptor: "Independent digital studio / KSA + BD",
  heroKicker: "Saudi Arabia · Bangladesh",
  heroTitle: "A professional digital presence that wins customers.",
  heroBody:
    "We design conversion-focused websites and run full-funnel digital marketing — paid ads, SEO, social, and WhatsApp automation — so your brand looks credible and generates qualified leads.",
  ctaPrimary: "Request a website",
  ctaSecondary: "View our work",
  offerTitle: "Website package",
  offerPrice: "1,000 SAR",
  offerBody:
    "A professional, modern website with lifetime support. Built to establish trust and convert visitors into inquiries.",
  servicesTitle: "Capabilities",
  servicesIntro: "End-to-end digital marketing and online infrastructure for growing businesses.",
  focusTitle: "Primary focus",
  focusBody:
    "We deliver a polished, customer-ready website that strengthens credibility and creates a reliable channel for new leads.",
  teamTitle: "Cross-border delivery",
  teamBody:
    "Specialists in Saudi Arabia and Bangladesh collaborate on strategy, production, and campaign management — with clear communication and accountable delivery.",
  legalTitle: "Legal support",
  legalBody:
    "Consultation and legal assistance through licensed Bangladeshi advocates, available when your business needs it.",
  projectsTitle: "Existing Projects",
  projectsEmpty: "Portfolio items will appear here once they are published from the admin panel.",
  viewLive: "Visit live site",
  viewDetails: "Case details",
  workTitle: "Recent activity",
  contactTitle: "Start a conversation",
  contactBody:
    "Tell us about your business goals. We will recommend a website, campaign, or growth plan that fits your market.",
  sendWhatsApp: "Message on WhatsApp",
  sendEmail: "Email the team",
  footerNote: "Digital strategy, websites, and paid media across Saudi Arabia and Bangladesh.",
  allCategories: "All",
  featured: "Featured",
  languageLabel: "বাংলা",
  whatWeDo: "What we do",
  servicesHeadline: "Built for the moment your customer decides.",
  pointOfView: "Our point of view",
  beyondBrief: "Beyond the brief",
  howWeWork: "How we work",
  selectedWork: "Selected work",
  workDescription: "Digital experiences, campaigns, and systems made to move a business forward.",
  motionFilm: "Motion and film",
  videoEditing: "Video Editing",
  clientPerspective: "Client perspective",
  reviews: "Reviews",
  posterBannerDesign: "Poster and Banner Design",
  posters: "Posters",
  banners: "Banners",
  viewFullDesign: "View full design",
  viewFullReview: "View full review",
  trackRecord: "Track record",
  completedOrders: "Completed orders",
  capability: "BST capability",
  previous: "Previous",
  next: "Next",
  openReview: "Open review image",
  closeReview: "Close review image",
  reviewImage: "Review image",
  clientReview: "Client review",
  clientReviewEnlarged: "Client review enlarged",
  openDesign: "Open design image",
  closeDesign: "Close design image",
  designImage: "Design image",
  designImageEnlarged: "Design image enlarged",
  openVideo: "Open video",
  closeVideo: "Close video",
  videoPlayer: "Video player",
  videoPreview: "Video preview",
  switchLanguage: "Language",
  tagline: "Websites, performance marketing, and growth systems.",
  whatsapp: "WhatsApp",
  email: "Email",
  showLess: "Show Less",
  seeAllProjects: "See All Projects",
  web: "Web",
  ads: "Ads",
  seo: "SEO",
  brand: "Brand",
  marquee: "Websites · Paid media · SEO · Brand",
  services: [
    "Professional website development — 1,000 SAR",
    "Facebook marketing",
    "YouTube marketing",
    "Instagram marketing",
    "Brand identity and graphic design",
    "Video, Reels, and ad production",
    "SEO and Google Business optimization",
    "Google, Meta, TikTok, and Snapchat ads",
    "WhatsApp marketing and automation",
    "Analytics and monthly reporting",
    "Full digital marketing programs",
    "Google Business Profile setup",
    "Legal support from Bangladeshi advocates",
  ],
};

export const defaultHeroTitles = {
  en: copy.heroTitle,
  bn: "এমন একটি পেশাদার ডিজিটাল উপস্থিতি, যা গ্রাহকদের আকৃষ্ট করে এবং ব্যবসায় জয়ী করে।",
  ar: "حضور رقمي احترافي يكسب العملاء.",
};

export const services = copy.services.map((label, index) => ({
  icon: String(index + 1).padStart(2, "0"),
  label,
}));
